controller:

  admin:
    username: admin
    password: admin123


  serviceType: LoadBalancer


  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - docker-workflow
    - configuration-as-code
    - blueocean
    - pipeline-stage-view
    - credentials
    - github
    - github-branch-source


  resources:

    requests:
      cpu: "500m"
      memory: "1Gi"

    limits:
      cpu: "1000m"
      memory: "2Gi"


persistence:

  enabled: false


agent:
  enabled: true

  image:
    repository: yousra314/jenkins-agent
    tag: latest

  workingDir: "/home/jenkins/agent"